const recipe = [
{From: "Armor Smith", NameCall: "LightKikko", Name: "Light Kikko", Materials: "Linen HaganeSteelBar BronzeBar StandardFittings", Quantity: "3 5 5 1"},
{From: "Armor Smith", NameCall: "HeavyKikko", Name: "Heavy Kikko", Materials: "NettleWeave HaganeSteelBar IronBar StandardFittings BrassBar", Quantity: "3 6 6 1 4"},
{From: "Armor Smith", NameCall: "TetsuJingasa", Name: "Tetsu Jingasa", Materials: "Flax HaganeSteelBar CopperBar StandardFittings", Quantity: "5 4 1 1"},
{From: "Armor Smith", NameCall: "BajoJingasa", Name: "Bajo Jingasa", Materials: "Flax HaganeSteelBar CopperBar StandardFittings", Quantity: "5 5 2 1"},
{From: "Armor Smith", NameCall: "LightO-yoroi", Name: "Light O-yoroi", Materials: "Silk HaganeSteelBar BronzeBar StandardFittings IronBar", Quantity: "4 4 4 1 4"},
{From: "Armor Smith", NameCall: "HeavyO-yoroi", Name: "Heavy O-yoroi", Materials: "Silk KawagneSteelBar IronBar ShiganeSteelBar StandardFittings GoldBar", Quantity: "6 2 3 5 1 3"},
{From: "Armor Smith", NameCall: "TatamiKabuto", Name: "Tatami Kabuto", Materials: "Linen BronzeBar HaganeSteelBar StandardFittings", Quantity: "2 4 3 1"},
{From: "Armor Smith", NameCall: "SujibachiKabuto", Name: "Sujibachi Kabuto", Materials: "Cloth IronBar KawagneSteelBar ShiganeSteelBar Silk StandardFittings", Quantity: "2 2 1 2 1 1"},
{From: "Armor Smith", NameCall: "SameKabuto", Name: "Same Kabuto", Materials: "Cloth IronBar KawagneSteelBar ShiganeSteelBar HigashiSteelBar StandardFittings", Quantity: "2 3 2 3 1 1"},
{From: "Armor Smith", NameCall: "HishiodoshiKabuto", Name: "Hishiodoshi Kabuto", Materials: "Cloth IronBar KawagneSteelBar ShiganeSteelBar HigashiSteelBar StandardFittings", Quantity: "2 3 2 3 1 1"},
{From: "Armor Smith", NameCall: "GenpeiKabuto", Name: "Genpei Kabuto", Materials: "Silk GoldBar KawagneSteelBar ShiganeSteelBar StandardFittings IronBar", Quantity: "3 3 2 3 1 3"},
{From: "Armor Smith", NameCall: "LightGyorin", Name: "Light Gyorin", Materials: "Cloth ShiganeSteelBar IronBar StandardFittings KawagneSteelBar HigashiSteelBar", Quantity: "3 4 4 1 2 2"},
{From: "Armor Smith", NameCall: "HeavyGyorin", Name: "Heavy Gyorin", Materials: "Cloth ShiganeSteelBar SilverBar KawagneSteelBar StandardFittings HigashiSteelBar", Quantity: "4 5 2 3 1 3"},
{From: "Armor Smith", NameCall: "LightTatami", Name: "Light Tatami", Materials: "Flax HaganeSteelBar CopperBar StandardFittings", Quantity: "15 7 3 1"},
{From: "Armor Smith", NameCall: "HeavyTatami", Name: "Heavy Tatami", Materials: "NettleWeave HaganeSteelBar BronzeBar StandardFittings Linen", Quantity: "2 8 4 1 2"},
{From: "Armor Smith", NameCall: "LightTosei", Name: "Light Tosei", Materials: "Cloth ShiganeSteelBar IronBar StandardFittings KawagneSteelBar HigashiSteelBar", Quantity: "3 3 4 1 4 2"},
{From: "Armor Smith", NameCall: "HeavyTosei", Name: "Heavy Tosei", Materials: "Cloth ShiganeSteelBar SilverBar KawagneSteelBar StandardFittings HigashiSteelBar", Quantity: "4 5 2 3 1 3"},
{From: "Armor Smith", NameCall: "LightDo-maru", Name: "Light Do-maru", Materials: "NettleWeave HaganeSteelBar BronzeBar StandardFittings HigashiSteelBar", Quantity: "3 6 4 1 1"},
{From: "Armor Smith", NameCall: "HeavyDo-maru", Name: "Heavy Do-maru", Materials: "Cloth KawagneSteelBar IronBar ShiganeSteelBar StandardFittings HigashiSteelBar", Quantity: "3 3 3 5 1 2"},
{From: "Armor Smith", NameCall: "KusariGusoku", Name: "Kusari Gusoku", Materials: "Silk ShiganeSteelBar IronBar StandardFittings KawagneSteelBar Cloth", Quantity: "2 3 3 1 2 3"},
{From: "Carpenter", NameCall: "OakHandle", Name: "Oak Handle", Materials: "OakLog", Quantity: "1"},
{From: "Carpenter", NameCall: "BirchHandle", Name: "Birch Handle", Materials: "BirchLog", Quantity: "1"},
{From: "Carpenter", NameCall: "WillowHandle", Name: "Willow Handle", Materials: "WillowLog", Quantity: "1"},
{From: "Carpenter", NameCall: "MapleHandle", Name: "Maple Handle", Materials: "MapleLog", Quantity: "1"},
{From: "Carpenter", NameCall: "PineHandle", Name: "Pine Handle", Materials: "PineLog", Quantity: "1"},
{From: "Carpenter", NameCall: "OakFittings", Name: "Oak Fittings", Materials: "OakLog", Quantity: "5"},
{From: "Carpenter", NameCall: "BirchFittings", Name: "Birch Fittings", Materials: "BirchLog", Quantity: "5"},
{From: "Carpenter", NameCall: "MapleFittings", Name: "Maple Fittings", Materials: "MapleLog", Quantity: "5"},
{From: "Carpenter", NameCall: "CherryFittings", Name: "Cherry Fittings", Materials: "CherryLog", Quantity: "5"},
{From: "Carpenter", NameCall: "PineFittings", Name: "Pine Fittings", Materials: "PineLog", Quantity: "5"},
{From: "Carpenter", NameCall: "WillowFittings", Name: "Willow Fittings", Materials: "WillowLog", Quantity: "5"},
{From: "Carpenter", NameCall: "TinFittings", Name: "Tin Fittings", Materials: "TinBar", Quantity: "5"},
{From: "Carpenter", NameCall: "BronzeFittings", Name: "Bronze Fittings", Materials: "BronzeBar", Quantity: "5"},
{From: "Carpenter", NameCall: "SilverFittings", Name: "Silver Fittings", Materials: "SilverBar", Quantity: "5"},
{From: "Carpenter", NameCall: "GoldFittings", Name: "Gold Fittings", Materials: "GoldBar", Quantity: "5"},
{From: "Carpenter", NameCall: "IronFittings", Name: "Iron Fittings", Materials: "IronBar", Quantity: "5"},
{From: "Carpenter", NameCall: "CopperFittings", Name: "Copper Fittings", Materials: "CopperBar", Quantity: "5"},
{From: "Clan Artisan", NameCall: "ClanFittings", Name: "Clan Fittings", Materials: "RedDye BlueDye YellowDye HaganeSteelBar PineLog Flax", Quantity: "1 1 1 1 1 2"},
{From: "Fabric Weaver", NameCall: "NettleWeave", Name: "Nettle Weave", Materials: "Ramie", Quantity: "3"},
{From: "Fabric Weaver", NameCall: "Cloth", Name: "Cloth", Materials: "Cotton", Quantity: "5"},
{From: "Fabric Weaver", NameCall: "Hachimaki", Name: "Hachimaki", Materials: "Linen Cloth StandardFittings", Quantity: "3 5 1"},
{From: "Fabric Weaver", NameCall: "Eboshi", Name: "Eboshi", Materials: "Linen Cloth StandardFittings", Quantity: "4 8 1"},
{From: "Fabric Weaver", NameCall: "Zukin", Name: "Zukin", Materials: "Cloth NettleWeave Silk", Quantity: "5 2 2"},
{From: "Fabric Weaver", NameCall: "WhiteShirt", Name: "White Shirt", Materials: "Cloth", Quantity: "3"},
{From: "Fabric Weaver", NameCall: "BlackShirt", Name: "Black Shirt", Materials: "Cloth BlackDye", Quantity: "3 2"},
{From: "Fabric Weaver", NameCall: "GreyShirt", Name: "Grey Shirt", Materials: "Cloth BlackDye WhiteDye", Quantity: "8 1 1"},
{From: "Fabric Weaver", NameCall: "BrownShirt", Name: "Brown Shirt", Materials: "Linen", Quantity: "4"},
{From: "Fabric Weaver", NameCall: "TanShirt", Name: "Tan Shirt", Materials: "Linen", Quantity: "4"},
{From: "Fabric Weaver", NameCall: "ClanShirt", Name: "Clan Shirt", Materials: "Cloth ClanFittings", Quantity: "3 1"},
{From: "Fabric Weaver", NameCall: "WhitePants", Name: "White Pants", Materials: "Cloth", Quantity: "3"},
{From: "Fabric Weaver", NameCall: "BlackPants", Name: "Black Pants", Materials: "Cloth BlackDye", Quantity: "3 2"},
{From: "Fabric Weaver", NameCall: "GreyPants", Name: "Grey Pants", Materials: "Cloth BlackDye WhiteDye", Quantity: "8 1 1"},
{From: "Fabric Weaver", NameCall: "BrownPants", Name: "Brown Pants", Materials: "Linen", Quantity: "4"},
{From: "Fabric Weaver", NameCall: "TanPants", Name: "Tan Pants", Materials: "Linen", Quantity: "4"},
{From: "Fabric Weaver", NameCall: "ClanPants", Name: "Clan Pants", Materials: "Cloth ClanFittings", Quantity: "3 1"},
{From: "Fishing Lodge", NameCall: "ApprenticeFishingPole", Name: "Apprentice Fishing Pole", Materials: "OakLog Linen", Quantity: "5 1"},
{From: "Fishing Lodge", NameCall: "JourneymanFishingPole", Name: "Journeyman Fishing Pole", Materials: "BirchLog Linen BronzeBar", Quantity: "5 1 2"},
{From: "Fishing Lodge", NameCall: "MasterFishingPole", Name: "Master Fishing Pole", Materials: "MapleLog Cloth BrassBar TinBar", Quantity: "5 1 2 2"},
{From: "Fishing Lodge", NameCall: "ApprenticeNet", Name: "Apprentice Net", Materials: "OakLog Linen", Quantity: "5 1"},
{From: "Fishing Lodge", NameCall: "JourneymanNet", Name: "Journeyman Net", Materials: "BirchLog BronzeBar Linen", Quantity: "5 2 1"},
{From: "Fishing Lodge", NameCall: "MasterNet", Name: "Master Net", Materials: "MapleLog Cloth BrassBar TinBar", Quantity: "5 1 2 2"},
{From: "Fletcher", NameCall: "SanmaiuchiHankyu", Name: "Sanmaiuchi Hankyu", Materials: "PineLog OakLog Flax", Quantity: "10 5 10"},
{From: "Fletcher", NameCall: "ShihodakeHankyu", Name: "Shihodake Hankyu", Materials: "BirchLog BronzeBar NettleWeave PineLog", Quantity: "10 5 1 5"},
{From: "Fletcher", NameCall: "SanbonhigoHankyu", Name: "Sanbonhigo Hankyu", Materials: "MapleLog BrassBar NettleWeave TinBar CherryLog", Quantity: "10 5 2 5 5"},
{From: "Fletcher", NameCall: "SanmaiuchiDaikyu", Name: "Sanmaiuchi Daikyu", Materials: "PineLog Flax OakLog", Quantity: "5 10 12"},
{From: "Fletcher", NameCall: "ShihodakeDaikyu", Name: "Shihodake Daikyu", Materials: "WillowLog BrassBar NettleWeave OakLog", Quantity: "12 5 2 5"},
{From: "Fletcher", NameCall: "SanbonhigoDaikyu", Name: "Sanbonhigo Daikyu", Materials: "CherryLog BrassBar NettleWeave TinBar MapleLog", Quantity: "12 5 3 5 5"},
{From: "Forge", NameCall: "CopperBar", Name: "Copper Bar", Materials: "Coal CopperOre", Quantity: "1 1"},
{From: "Forge", NameCall: "HaganeSteelBar", Name: "Hagane Steel Bar", Materials: "Coal IronOre Clay", Quantity: "1 1 1"},
{From: "Forge", NameCall: "TinBar", Name: "Tin Bar", Materials: "TinOre Coal", Quantity: "1 1"},
{From: "Forge", NameCall: "LeadBar", Name: "Lead Bar", Materials: "LeadOre Coal", Quantity: "4 3"},
{From: "Forge", NameCall: "BrassBar", Name: "Brass Bar", Materials: "Coal CopperOre ZincOre", Quantity: "3 2 2"},
{From: "Forge", NameCall: "IronBar", Name: "Iron Bar", Materials: "Coal IronOre ZincOre", Quantity: "2 4 2"},
{From: "Forge", NameCall: "ShiganeSteelBar", Name: "Shigane Steel Bar", Materials: "Coal Clay IronOre ZincOre", Quantity: "2 2 4 5"},
{From: "Forge", NameCall: "SilverBar", Name: "Silver Bar", Materials: "Coal SilverOre", Quantity: "8 4"},
{From: "Forge", NameCall: "KawagneSteelBar", Name: "Kawagne Steel Bar", Materials: "Coal Clay IronOre ZincOre NickelOre", Quantity: "5 4 5 2 5"},
{From: "Forge", NameCall: "GoldBar", Name: "Gold Bar", Materials: "Coal GoldOre", Quantity: "16 8"},
{From: "Forge", NameCall: "BronzeBar", Name: "Bronze Bar", Materials: "CopperOre TinOre Coal", Quantity: "2 3 3"},
{From: "Gunsmith", NameCall: "Hazamatutu", Name: "Hazamatutu", Materials: "CherryLog ShiganeSteelBar BrassBar TinBar MapleLog Tsutsu", Quantity: "12 3 3 3 5 1"},
{From: "Gunsmith", NameCall: "Bajoututu", Name: "Bajoututu", Materials: "MapleLog ShiganeSteelBar BrassBar TinBar Tsutsu", Quantity: "12 3 3 3 1"},
{From: "Gunsmith", NameCall: "Hinawaju", Name: "Hinawaju", Materials: "MapleLog ShiganeSteelBar BrassBar TinBar CherryLog Tsutsu", Quantity: "10 3 3 3 5 1"},
{From: "Kiln", NameCall: "SmallDonabe", Name: "Small Donabe", Materials: "Coal Charcoal Clay", Quantity: "5 2 10"},
{From: "Kiln", NameCall: "MediumDonabe", Name: "Medium Donabe", Materials: "Coal Charcoal Clay", Quantity: "7 4 15"},
{From: "Kiln", NameCall: "GrenadeCasing", Name: "Grenade Casing", Materials: "Coal Charcoal Clay", Quantity: "2 3 5"},
{From: "Kiln", NameCall: "SmallVessel", Name: "Small Vessel", Materials: "Coal Charcoal Clay", Quantity: "4 6 10"},
{From: "Metal Worker", NameCall: "SilverTrimmedCopperFittings", Name: "Silver Trimmed Copper Fittings", Materials: "CopperBar PineLog Flax SilverBar", Quantity: "8 1 2 1"},
{From: "Metal Worker", NameCall: "SilverTrimmedTinFittings", Name: "Silver Trimmed Tin Fittings", Materials: "TinBar SilverBar PineLog Flax", Quantity: "8 1 1 2"},
{From: "Metal Worker", NameCall: "SilverTrimmedBronzeFittings", Name: "Silver Trimmed Bronze Fittings", Materials: "BronzeBar SilverBar PineLog Flax", Quantity: "8 1 1 2"},
{From: "Metal Worker", NameCall: "SilverTrimmedIronFittings", Name: "Silver Trimmed Iron Fittings", Materials: "IronBar SilverBar PineLog Flax", Quantity: "8 1 1 2"},
{From: "Metal Worker", NameCall: "GoldTrimmedCopperFittings", Name: "Gold Trimmed Copper Fittings", Materials: "CopperBar PineLog Flax GoldBar", Quantity: "8 1 2 1"},
{From: "Metal Worker", NameCall: "GoldTrimmedTinFittings", Name: "Gold Trimmed Tin Fittings", Materials: "TinBar GoldBar PineLog Flax", Quantity: "8 1 1 2"},
{From: "Metal Worker", NameCall: "GoldTrimmedBronzeFittings", Name: "Gold Trimmed Bronze Fittings", Materials: "BronzeBar GoldBar PineLog Flax", Quantity: "8 1 1 2"},
{From: "Metal Worker", NameCall: "GoldTrimmedIronFittings", Name: "Gold Trimmed Iron Fittings", Materials: "IronBar GoldBar PineLog Flax", Quantity: "8 1 1 2"},
{From: "Metal Worker", NameCall: "Happuri", Name: "Happuri", Materials: "HaganeSteelBar ShiganeSteelBar Linen", Quantity: "1 2 2"},
{From: "Metal Worker", NameCall: "Hanbo", Name: "Hanbo", Materials: "Linen IronBar ShiganeSteelBar", Quantity: "2 1 2"},
{From: "Metal Worker", NameCall: "Menpo", Name: "Menpo", Materials: "Cloth IronBar ShiganeSteelBar", Quantity: "2 2 3"},
{From: "Metal Worker", NameCall: "UreshiiMenpo", Name: "Ureshii Menpo", Materials: "Cloth IronBar ShiganeSteelBar", Quantity: "2 2 3"},
{From: "Metal Worker", NameCall: "KanashiiMenpo", Name: "Kanashii Menpo", Materials: "Cloth IronBar ShiganeSteelBar", Quantity: "2 2 3"},
{From: "Metal Worker", NameCall: "Makibishi", Name: "Makibishi", Materials: "IronBar", Quantity: "2"},
{From: "Smithy", NameCall: "CopperAxe", Name: "Copper Axe", Materials: "CopperBar PineHandle", Quantity: "3 1"},
{From: "Smithy", NameCall: "BronzeAxe", Name: "Bronze Axe", Materials: "BronzeBar PineHandle", Quantity: "5 1"},
{From: "Smithy", NameCall: "CopperPick", Name: "Copper Pick", Materials: "CopperBar PineHandle", Quantity: "3 1"},
{From: "Smithy", NameCall: "BronzePick", Name: "Bronze Pick", Materials: "BronzeBar PineHandle", Quantity: "5 1"},
{From: "Smithy", NameCall: "MaruTanto", Name: "Maru Tanto", Materials: "HaganeSteelBar StandardFittings", Quantity: "3 1"},
{From: "Smithy", NameCall: "MaruSuYari", Name: "Maru Su Yari", Materials: "HaganeSteelBar PineLog PineFittings", Quantity: "2 5 1"},
{From: "Smithy", NameCall: "MaruKatana", Name: "Maru Katana", Materials: "HaganeSteelBar StandardFittings", Quantity: "5 1"},
{From: "Smithy", NameCall: "LightTatami", Name: "Light Tatami", Materials: "Flax HaganeSteelBar CopperBar StandardFittings", Quantity: "15 7 3 1"},
{From: "Smithy", NameCall: "TetsuJingasa", Name: "Tetsu Jingasa", Materials: "Flax HaganeSteelBar CopperBar StandardFittings", Quantity: "5 4 1 1"},
{From: "Smithy", NameCall: "BajoJingasa", Name: "Bajo Jingasa", Materials: "Flax HaganeSteelBar CopperBar StandardFittings", Quantity: "5 5 2 1"},
{From: "Sword Smith", NameCall: "MaruKatana", Name: "Maru Katana", Materials: "HaganeSteelBar StandardFittings", Quantity: "5 1"},
{From: "Sword Smith", NameCall: "HonsanmaiKatana", Name: "Honsanmai Katana", Materials: "HaganeSteelBar ShiganeSteelBar StandardFittings", Quantity: "5 3 1"},
{From: "Sword Smith", NameCall: "SoshuKatana", Name: "Soshu Katana", Materials: "HaganeSteelBar ShiganeSteelBar KawagneSteelBar SilverBar NishiSteelBar StandardFittings", Quantity: "3 3 3 1 2 1"},
{From: "Sword Smith", NameCall: "Tachi", Name: "Tachi", Materials: "BrassBar ShiganeSteelBar KawagneSteelBar SilverBar StandardFittings NishiSteelBar", Quantity: "2 4 4 2 1 3"},
{From: "Sword Smith", NameCall: "Wakizashi", Name: "Wakizashi", Materials: "HaganeSteelBar ShiganeSteelBar KawagneSteelBar SilverBar StandardFittings", Quantity: "3 2 2 1 1"},
{From: "Sword Smith", NameCall: "Kodachi", Name: "Kodachi", Materials: "NishiSteelBar ShiganeSteelBar KawagneSteelBar GoldBar StandardFittings", Quantity: "2 3 3 2 1"},
{From: "Sword Smith", NameCall: "MaruTanto", Name: "Maru Tanto", Materials: "HaganeSteelBar StandardFittings", Quantity: "3 1"},
{From: "Sword Smith", NameCall: "HonsanmaiTanto", Name: "Honsanmai Tanto", Materials: "HaganeSteelBar ShiganeSteelBar StandardFittings", Quantity: "3 1 1"},
{From: "Sword Smith", NameCall: "SoshuTanto", Name: "Soshu Tanto", Materials: "HaganeSteelBar ShiganeSteelBar StandardFittings KawagneSteelBar", Quantity: "2 2 1 2"},
{From: "Workshop", NameCall: "CopperAxe", Name: "Copper Axe", Materials: "CopperBar PineHandle", Quantity: "3 1"},
{From: "Workshop", NameCall: "BronzeAxe", Name: "Bronze Axe", Materials: "BronzeBar PineHandle", Quantity: "5 1"},
{From: "Workshop", NameCall: "IronAxe", Name: "Iron Axe", Materials: "IronBar PineHandle", Quantity: "7 1"},
{From: "Workshop", NameCall: "SteelAxe", Name: "Steel Axe", Materials: "HaganeSteelBar ShiganeSteelBar KawagneSteelBar PineHandle", Quantity: "5 3 2 1"},
{From: "Workshop", NameCall: "CopperPick", Name: "Copper Pick", Materials: "CopperBar PineHandle", Quantity: "3 1"},
{From: "Workshop", NameCall: "BronzePick", Name: "Bronze Pick", Materials: "BronzeBar PineHandle", Quantity: "5 1"},
{From: "Workshop", NameCall: "IronPick", Name: "Iron Pick", Materials: "IronBar PineHandle", Quantity: "7 1"},
{From: "Workshop", NameCall: "SteelPick", Name: "Steel Pick", Materials: "HaganeSteelBar ShiganeSteelBar KawagneSteelBar PineHandle", Quantity: "5 3 2 1"},
{From: "Yari Smith", NameCall: "MaruSuYari", Name: "Maru Su Yari", Materials: "HaganeSteelBar PineLog PineFittings", Quantity: "2 5 1"},
{From: "Yari Smith", NameCall: "HonsanmaiSuYari", Name: "Honsanmai Su Yari", Materials: "HaganeSteelBar BirchLog ShiganeSteelBar BirchFittings", Quantity: "2 5 1 1"},
{From: "Yari Smith", NameCall: "SoshuSuYari", Name: "Soshu Su Yari", Materials: "HaganeSteelBar MapleLog ShiganeSteelBar KawagneSteelBar MapleFittings", Quantity: "2 5 2 1 1"},
{From: "Yari Smith", NameCall: "JumonjiYari", Name: "Jumonji Yari", Materials: "CherryLog ShiganeSteelBar KawagneSteelBar CherryFittings NishiSteelBar", Quantity: "5 5 3 1 3"},
{From: "Backpack", NameCall: "BlueDye", Name: "Blue Dye", Materials: "Clay Charcoal Blueberry", Quantity: "1 1 1"},
{From: "Backpack", NameCall: "WhiteDye", Name: "White Dye", Materials: "Clay Charcoal Saltpeter", Quantity: "1 1 5"},
{From: "Backpack", NameCall: "RedDye", Name: "Red Dye", Materials: "Clay Charcoal Raspberry", Quantity: "1 1 1"},
{From: "Backpack", NameCall: "YellowDye", Name: "Yellow Dye", Materials: "Clay Charcoal NegiOnion", Quantity: "1 1 1"},
{From: "Backpack", NameCall: "BlackDye", Name: "Black Dye", Materials: "Clay Charcoal LeadOre", Quantity: "1 1 2"},
{From: "Backpack", NameCall: "Gunpowder", Name: "Gunpowder", Materials: "Saltpeter Charcoal Sulfur", Quantity: "3 2 1"},
{From: "Backpack", NameCall: "Smokepowder", Name: "Smokepowder", Materials: "Gunpowder Sulfur Flax", Quantity: "1 3 10"},
{From: "Backpack", NameCall: "SoyOil", Name: "Soy Oil", Materials: "SoyPods", Quantity: "3"},
{From: "Backpack", NameCall: "Tetrodotoxin", Name: "Tetrodotoxin", Materials: "Fugu", Quantity: "1"},
{From: "Backpack", NameCall: "SmokeBomb", Name: "Smoke Bomb", Materials: "Smokepowder GrenadeCasing NettleWeave", Quantity: "1 1 1"},
{From: "Backpack", NameCall: "FireBomb", Name: "Fire Bomb", Materials: "SoyOil GrenadeCasing NettleWeave", Quantity: "3 1 1"},
{From: "Backpack", NameCall: "Amaterasu'sDefense", Name: "Amaterasu's Defense", Materials: "SmallVessel Alisma Blueberry", Quantity: "1 3 5"},
{From: "Backpack", NameCall: "Dough", Name: "Dough", Materials: "Wheat", Quantity: "3"},
{From: "Backpack", NameCall: "PreparedMullet", Name: "Prepared Mullet", Materials: "Mullet Saltpeter", Quantity: "1 1"},
{From: "Backpack", NameCall: "PreparedTrout", Name: "Prepared Trout", Materials: "Trout Saltpeter", Quantity: "1 1"},
{From: "Backpack", NameCall: "PreparedSalmon", Name: "Prepared Salmon", Materials: "Salmon Saltpeter", Quantity: "1 1"},
{From: "Backpack", NameCall: "PreparedSturgeon", Name: "Prepared Sturgeon", Materials: "Sturgeon Saltpeter", Quantity: "1 1"},
{From: "Backpack", NameCall: "PreparedClams", Name: "Prepared Clams", Materials: "AsariClam Saltpeter", Quantity: "3 1"},
{From: "Backpack", NameCall: "PreparedFugu", Name: "Prepared Fugu", Materials: "Fugu Saltpeter", Quantity: "1 1"},
{From: "Backpack", NameCall: "Soybeans", Name: "Soybeans", Materials: "SoyPods", Quantity: "3"},
{From: "Backpack", NameCall: "SmallBed", Name: "Small Bed", Materials: "Linen", Quantity: "1"},
{From: "Backpack", NameCall: "CrudeTorch", Name: "Crude Torch", Materials: "Flax PineLog Coal", Quantity: "2 1 1"},
{From: "Backpack", NameCall: "CrudePot", Name: "Crude Pot", Materials: "CopperBar PineLog", Quantity: "3 2"},
{From: "Backpack", NameCall: "MealBox", Name: "Meal Box", Materials: "PineLog", Quantity: "5"},
{From: "Backpack", NameCall: "CrudeFishingPole", Name: "Crude Fishing Pole", Materials: "PineLog Flax", Quantity: "4 10"},
{From: "Backpack", NameCall: "Sashimono", Name: "Sashimono", Materials: "PineLog Linen TinBar ClanFittings", Quantity: "2 2 1 1"},
{From: "Backpack", NameCall: "CrudeNet", Name: "Crude Net", Materials: "PineLog Flax", Quantity: "4 10"},
{From: "Backpack", NameCall: "CrudeBowl", Name: "Crude Bowl", Materials: "PineLog", Quantity: "3"},
{From: "Backpack", NameCall: "StonePick", Name: "Stone Pick", Materials: "Flax Bamboo Stone", Quantity: "5 1 2"},
{From: "Backpack", NameCall: "StoneAxe", Name: "Stone Axe", Materials: "Flax Bamboo Stone", Quantity: "5 1 2"},
{From: "Backpack", NameCall: "CrudeYari", Name: "Crude Yari", Materials: "Bamboo", Quantity: "3"},
{From: "Backpack", NameCall: "FusetakeYumi", Name: "Fusetake Yumi", Materials: "PineLog Flax", Quantity: "8 5"},
{From: "Backpack", NameCall: "OakHandle", Name: "Oak Handle", Materials: "OakLog", Quantity: "1"},
{From: "Backpack", NameCall: "BirchHandle", Name: "Birch Handle", Materials: "BirchLog", Quantity: "1"},
{From: "Backpack", NameCall: "WillowHandle", Name: "Willow Handle", Materials: "WillowLog", Quantity: "1"},
{From: "Backpack", NameCall: "MapleHandle", Name: "Maple Handle", Materials: "MapleLog", Quantity: "1"},
{From: "Backpack", NameCall: "PineHandle", Name: "Pine Handle", Materials: "PineLog", Quantity: "1"},
{From: "Backpack", NameCall: "CherryHandle", Name: "Cherry Handle", Materials: "CherryLog", Quantity: "1"},
{From: "Backpack", NameCall: "Linen", Name: "Linen", Materials: "Flax", Quantity: "10"},
{From: "Backpack", NameCall: "PineFittings", Name: "Pine Fittings", Materials: "PineLog", Quantity: "5"},
{From: "Backpack", NameCall: "OakFittings", Name: "Oak Fittings", Materials: "OakLog", Quantity: "5"},
{From: "Backpack", NameCall: "BirchFittings", Name: "Birch Fittings", Materials: "BirchLog", Quantity: "5"},
{From: "Backpack", NameCall: "WillowFittings", Name: "Willow Fittings", Materials: "WillowLog", Quantity: "5"},
{From: "Backpack", NameCall: "MapleFittings", Name: "Maple Fittings", Materials: "MapleLog", Quantity: "5"},
{From: "Backpack", NameCall: "CherryFittings", Name: "Cherry Fittings", Materials: "CherryLog", Quantity: "5"},
{From: "Backpack", NameCall: "StandardCopperFittings", Name: "Standard Copper Fittings", Materials: "CopperBar PineLog Flax", Quantity: "5 1 2"},
{From: "Backpack", NameCall: "StandardTinFittings", Name: "Standard Tin Fittings", Materials: "TinBar PineLog Flax", Quantity: "5 1 2"},
{From: "Backpack", NameCall: "StandardBronzeFittings", Name: "Standard Bronze Fittings", Materials: "BronzeBar PineLog Flax", Quantity: "5 1 2"},
{From: "Backpack", NameCall: "StandardFittings", Name: "Standard Fittings", Materials: "HaganeSteelBar PineLog Flax", Quantity: "1 1 2"},
{From: "Backpack", NameCall: "StandardIronFittings", Name: "Standard Iron Fittings", Materials: "IronBar PineLog Flax", Quantity: "5 1 2"},
{From: "Backpack", NameCall: "RedFittings", Name: "Red Fittings", Materials: "HaganeSteelBar PineLog Flax RedDye", Quantity: "1 1 2 2"},
{From: "Backpack", NameCall: "BlackFittings", Name: "Black Fittings", Materials: "HaganeSteelBar PineLog Flax BlackDye", Quantity: "1 1 2 2"},
{From: "Backpack", NameCall: "BlueFittings", Name: "Blue Fittings", Materials: "HaganeSteelBar PineLog Flax BlueDye", Quantity: "1 1 2 2"},
{From: "Backpack", NameCall: "YellowFittings", Name: "Yellow Fittings", Materials: "HaganeSteelBar PineLog Flax YellowDye", Quantity: "1 1 2 2"},
{From: "Backpack", NameCall: "WhiteFittings", Name: "White Fittings", Materials: "HaganeSteelBar PineLog Flax WhiteDye", Quantity: "1 1 2 2"},
{From: "Backpack", NameCall: "CopperArrow", Name: "Copper Arrow", Materials: "PineLog CopperArrowheads", Quantity: "1 1"},
{From: "Backpack", NameCall: "BronzeArrow", Name: "Bronze Arrow", Materials: "PineLog BronzeArrowheads", Quantity: "1 1"},
{From: "Backpack", NameCall: "IronArrow", Name: "Iron Arrow", Materials: "BirchLog IronArrowheads", Quantity: "1 1"},
{From: "Backpack", NameCall: "SteelArrow", Name: "Steel Arrow", Materials: "MapleLog BrassBar SteelArrowheads", Quantity: "1 1 1"},
{From: "Backpack", NameCall: "KaburaArrow", Name: "Kabura Arrow", Materials: "MapleLog IronBar RedDye BlackDye", Quantity: "1 1 1 1"},
{From: "Backpack", NameCall: "StoneArrow", Name: "Stone Arrow", Materials: "Bamboo StoneArrowheads", Quantity: "1 1"},
{From: "Backpack", NameCall: "StoneArrowheads", Name: "Stone Arrowheads", Materials: "Stone", Quantity: "1"},
{From: "Backpack", NameCall: "StrawKasa", Name: "Straw Kasa", Materials: "Flax PineLog", Quantity: "15 3"},
{From: "Backpack", NameCall: "StrawGasa", Name: "Straw Gasa", Materials: "Flax BirchLog", Quantity: "15 3"},
{From: "Backpack", NameCall: "CopperArrowheads", Name: "Copper Arrowheads", Materials: "CopperBar", Quantity: "1"},
{From: "Backpack", NameCall: "BronzeArrowheads", Name: "Bronze Arrowheads", Materials: "BronzeBar", Quantity: "1"},
{From: "Backpack", NameCall: "IronArrowheads", Name: "Iron Arrowheads", Materials: "IronBar", Quantity: "1"},
{From: "Backpack", NameCall: "SteelArrowheads", Name: "Steel Arrowheads", Materials: "ShiganeSteelBar", Quantity: "1"},
{From: "Backpack", NameCall: "5MonmeRound", Name: "5 Monme Round", Materials: "LeadBar Gunpowder", Quantity: "1 2"},
{From: "Backpack", NameCall: "7MonmeRound", Name: "7 Monme Round", Materials: "LeadBar Gunpowder", Quantity: "1 2"},
{From: "Backpack", NameCall: "EnkeiTsuba", Name: "Enkei Tsuba", Materials: "HaganeSteelBar Linen", Quantity: "3 1"},
{From: "Backpack", NameCall: "KakuTsuba", Name: "Kaku Tsuba", Materials: "HaganeSteelBar Linen", Quantity: "3 1"},
{From: "Backpack", NameCall: "OtafukuTsuba", Name: "Otafuku Tsuba", Materials: "HaganeSteelBar Linen", Quantity: "3 1"},
{From: "Backpack", NameCall: "MokkoTsuba", Name: "Mokko Tsuba", Materials: "HaganeSteelBar Linen", Quantity: "3 1"},
{From: "Special Weapon Smith", NameCall: "Naginata", Name: "Naginata", Materials: "ShiganeSteelBar KawagneSteelBar SilverBar BlessedRedwood CherryFittings CherryLog", Quantity: "4 4 2 5 1 5"},
{From: "Special Weapon Smith", NameCall: "Kanabo", Name: "Kanabo", Materials: "ShiganeSteelBar KawagneSteelBar IronBar CherryLog BlessedRedwood CherryFittings", Quantity: "2 4 8 5 8 1"},
{From: "Special Weapon Smith", NameCall: "Kama", Name: "Kama", Materials: "NishiSteelBar ShiganeSteelBar KawagneSteelBar GoldBar CherryLog", Quantity: "3 3 3 2 5"},
]

const Discord = require('discord.js');
module.exports = {
    name: 'help',
    description: "this is a help command!",
    execute(message, args){
        const embed = new Discord.MessageEmbed();
        embed.setTitle('Commands:');
        embed.setColor('#f4c871');
        embed.setAuthor('made by Dub', 'https://i.imgur.com/Rn9muMO.png', 'https://www.roblox.com/users/93839005/profile');
        embed.setThumbnail('https://t1.rbxcdn.com/1194a83cefa36aae9055f96b0165858e');
        embed.addField('?raid','give raids info');
        embed.addField('?hheeggeell','pls dont use');
        message.channel.send(embed);
    }
}

